# Generated by Django 3.0.4 on 2020-07-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200706_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='image',
            new_name='blog_image',
        ),
    ]
