# Generated by Django 3.0.4 on 2020-07-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpage_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
